version: '3.8'
services:
  redis:
    image: redis:8.0-rc1-alpine3.21
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server","--appendonly","yes"]
volumes:
  redis-data: